import "./globals.css";
import Providers from "./providers";

export const metadata = {
  title: "Chat Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col" cz-shortcut-listen="true">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
